export enum TransactionErrorCode {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  NETWORK_CONGESTION = 'NETWORK_CONGESTION',
  INVALID_NONCE = 'INVALID_NONCE',
  SIGNATURE_VERIFICATION_FAILED = 'SIGNATURE_VERIFICATION_FAILED',
  CONTRACT_ERROR = 'CONTRACT_ERROR',
  UNKNOWN = 'UNKNOWN'
}

export enum RecoveryAction {
  RETRY = 'RETRY',
  INCREASE_FEE = 'INCREASE_FEE',
  UPDATE_NONCE = 'UPDATE_NONCE',
  MANUAL_INTERVENTION = 'MANUAL_INTERVENTION'
}
